<?php
namespace CPTBuilder\CodeGenerator;

use CPTBuilder\Core\Plugin;
use CPTBuilder\PostTypes\PostTypeManager;
use CPTBuilder\PostTypes\PostTypeRepository;
use CPTBuilder\Taxonomies\TaxonomyManager;
use CPTBuilder\Taxonomies\TaxonomyRepository;

defined( 'ABSPATH' ) || exit;

/**
 * Generates portable PHP for the configured structures.
 */
class CodeGenerator {

	/** @var Plugin */
	private $plugin;

	public function __construct( Plugin $plugin ) {
		$this->plugin = $plugin;
	}

	public function generate_all(): string {
		$chunks = array();

		foreach ( $this->plugin->get( PostTypeRepository::class )->all() as $config ) {
			$chunks[] = $this->generate_post_type( $config );
		}
		foreach ( $this->plugin->get( TaxonomyRepository::class )->all() as $config ) {
			$chunks[] = $this->generate_taxonomy( $config );
		}

		if ( empty( $chunks ) ) {
			return '// ' . __( 'No structures configured yet.', 'cpt-builder' );
		}

		return "<?php\n/**\n * Generated by CPT Builder " . CPTB_VERSION . "\n */\n\n" . implode( "\n", $chunks );
	}

	public function generate_post_type( array $config ): string {
		$args = $this->plugin->get( PostTypeManager::class )->build_args( $config );

		return "add_action( 'init', function () {\n"
			. "\tregister_post_type(\n"
			. "\t\t" . var_export( $config['key'], true ) . ",\n"
			. "\t\t" . $this->export_value( $args, 2 ) . "\n"
			. "\t);\n"
			. "} );\n";
	}

	public function generate_taxonomy( array $config ): string {
		$args       = $this->plugin->get( TaxonomyManager::class )->build_args( $config );
		$post_types = array_values( (array) ( $config['post_types'] ?? array() ) );

		return "add_action( 'init', function () {\n"
			. "\tregister_taxonomy(\n"
			. "\t\t" . var_export( $config['key'], true ) . ",\n"
			. "\t\t" . $this->export_value( $post_types, 2 ) . ",\n"
			. "\t\t" . $this->export_value( $args, 2 ) . "\n"
			. "\t);\n"
			. "} );\n";
	}

	/**
	 * Export a value as readable short-syntax PHP.
	 *
	 * @param mixed $value Value.
	 * @param int   $depth Indentation depth (tabs).
	 */
	private function export_value( $value, int $depth ): string {
		if ( ! is_array( $value ) ) {
			return var_export( $value, true );
		}

		if ( empty( $value ) ) {
			return '[]';
		}

		$indent  = str_repeat( "\t", $depth );
		$inner   = str_repeat( "\t", $depth + 1 );
		$is_list = array_keys( $value ) === range( 0, count( $value ) - 1 );
		$lines   = array();

		foreach ( $value as $key => $item ) {
			$prefix  = $is_list ? '' : var_export( (string) $key, true ) . ' => ';
			$lines[] = $inner . $prefix . $this->export_value( $item, $depth + 1 ) . ',';
		}

		return "[\n" . implode( "\n", $lines ) . "\n" . $indent . ']';
	}
}
